# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

compute_cvdynseg_cpp <- function(data_mat, segthr, lambda_set, n_folds, ncol, nrow, create_pen_func) {
    .Call(`_bincpd_compute_cvdynseg_cpp`, data_mat, segthr, lambda_set, n_folds, ncol, nrow, create_pen_func)
}

compute_cvseg_cpp <- function(data_mat, segthr, n_folds, ncol, nrow) {
    .Call(`_bincpd_compute_cvseg_cpp`, data_mat, segthr, n_folds, ncol, nrow)
}

compute_dynseg_cpp <- function(data_mat, ncol, segthr, pen_func) {
    .Call(`_bincpd_compute_dynseg_cpp`, data_mat, ncol, segthr, pen_func)
}

compute_hierseg_cpp <- function(data_matrix, n, m, pen_func) {
    .Call(`_bincpd_compute_hierseg_cpp`, data_matrix, n, m, pen_func)
}

