# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

compute_cvdynseg_cpp <- function(data_mat, segthr, lambda_set, n_folds, ncol, nrow, create_pen_func) {
    .Call(`_bincpd_compute_cvdynseg_cpp`, data_mat, segthr, lambda_set, n_folds, ncol, nrow, create_pen_func)
}

compute_cvseg_cpp <- function(data_mat, segthr, n_folds, ncol, nrow) {
    .Call(`_bincpd_compute_cvseg_cpp`, data_mat, segthr, n_folds, ncol, nrow)
}

compute_dynseg_cpp <- function(data_mat, ncol, segthr, pen_func) {
    .Call(`_bincpd_compute_dynseg_cpp`, data_mat, ncol, segthr, pen_func)
}

compute_hierseg_cpp <- function(data_matrix, n, m, pen_func) {
    .Call(`_bincpd_compute_hierseg_cpp`, data_matrix, n, m, pen_func)
}

#' @title
#' Rand Index Function for change point detection
#'
#' @description
#' Computes the rand Index (non-adjusted) for the change point sets. A specific
#' equation for change point detection is used to make the computation faster.
#' Proof of correctness of the equation is given in the dissertation.
#'
#' @param cp1 Change point set for model 1 or true change point set.
#' @param cp2 Change point set for model 2 or true change point set.
#' @param m The size of the vector array.
#'
compute_rand <- function(cp1, cp2, m) {
    .Call(`_bincpd_compute_rand`, cp1, cp2, m)
}

#' @title
#' Hausdorff distance metric
#'
#' @description
#' Computes the Hausdorff distance between change point sets.
#'
#' @param cp1 Change point set for model 1 or true change point set.
#' @param cp2 Change point set for model 2 or true change point set.
compute_hausdorff <- function(cp1, cp2) {
    .Call(`_bincpd_compute_hausdorff`, cp1, cp2)
}

#' @title
#' Symmetric difference metric
#'
#' @description
#' Computes the size of the symmetric difference between two change point
#' detection sets
#'
#' @param cp1 Change point set for model 1 or true change point set.
#' @param cp2 Change point set for model 2 or true change point set.
compute_symdiff <- function(cp1, cp2) {
    .Call(`_bincpd_compute_symdiff`, cp1, cp2)
}

