# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

build_matrices_cpp__ <- function(data_mat) {
    .Call('_bincpd_build_matrices_cpp__', PACKAGE = 'bincpd', data_mat)
}

comp_dynseg_cpp__ <- function(loglike_mat, p_mat, segthr = 100L) {
    .Call('_bincpd_comp_dynseg_cpp__', PACKAGE = 'bincpd', loglike_mat, p_mat, segthr)
}

comp_dynseg_cpp_fast__ <- function(loglike_mat, p_mat, ncol, segthr = 100L) {
    .Call('_bincpd_comp_dynseg_cpp_fast__', PACKAGE = 'bincpd', loglike_mat, p_mat, ncol, segthr)
}

hierarchical_algorithm_cpp <- function(data_matrix, n, m, pen_func) {
    .Call('_bincpd_hierarchical_algorithm_cpp', PACKAGE = 'bincpd', data_matrix, n, m, pen_func)
}

